### ISSUE TITLE
[SidePanel]: Scrolling behavior breaks when panel loads without a scrollbar and the screen height shrinks

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#1056]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

I see this in my program as well as in the latest [Cloud & Cognitive storybook here](https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-released-sidepanel--panel-with-second-step).

When the SidePanel is first loaded at full height without a scrollbar, the scrolling behavior for the panel's title breaks when the resizing the window height.

I do not see this issue when the SidePanel is first loaded with a scrollbar, and later adjust the window height.

I see this in Chrome & Firefox.

## Steps to reproduce the issue

1. In the C&CS Storybook under SidePanel > Panel with Second Step: Open the SidePanel so it loads at full height without a scrollbar
2. Shrink your window height smaller until a scrollbar within the panel appears
3. Scroll the panel and notice the panel's title is no longer shrinking and transitioning as intended

## Additional information

https://user-images.githubusercontent.com/3118961/126699308-0fe9c83a-3ecf-4821-9a0c-0d04542fcfe8.mov

**Comment by matthewgallo** [comment]
Hey @lily-peng, this will be addressed with https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1064

**Comment by matthewgallo** [comment]
Fix is released is version `@carbon/ibm-cloud-cognitive@0.61.2`. Feel free to reopen if you run into any other issues @lily-peng

**Comment by lily-peng** [comment]
Hi @matthewgallo, thanks for fixing it so quickly. However, I still see the same issue from my recording in the storybook (and in my application). Unless I am missing something, I don't think this issue was fixed?

**Comment by matthewgallo** [comment]
Ok, this should be fixed this now @lily-peng. Thanks for bringing it back up. `@carbon/ibm-cloud-cognitive@0.64.1`. As always, if this isn't behaving as expected please reopen!
